export const DATA_PRODUCT_NAMES = [
  "Hp laptop fire",
  "Lenovo desktop - xq",
  "Mac studio Max",
  "Mac studio Ultra",
  "Lg monitor Ultra",
  "Lg monitor fs2",
  "Lg monitor Ultra-Blue",
];

export const DATA_PRODUCTS = [
  {
    id: 1,
    title: "Hp laptop fire",
    price: 34000,
    count: 5,
    description: "lorem lorem lorem",
    category: "electronics",
  },
  {
    id: 2,
    title: "Lenovo laptop fire",
    price: 34000,
    count: 2,
    description: "lorem lorem lorem",
    category: "electronics",
  },
  {
    id: 4,
    title: "Asus laptop fire",
    price: 44000,
    count: 5,
    description: "lorem lorem lorem",
    category: "electronics",
  },
  {
    id: 12,
    title: "Monster laptop fire",
    price: 32000,
    count: 15,
    description: "lorem lorem lorem",
    category: "electronics",
  },
  {
    id: 24,
    title: "Casper laptop fire",
    price: 24000,
    count: 3,
    description: "lorem lorem lorem",
    category: "electronics",
  },
  {
    id: 240,
    title: "Polo T-shirt",
    price: 750,
    count: 3,
    description: "lorem lorem lorem",
    category: "textile",
  },
  {
    id: 223,
    title: "Mavi Jeans Pantolon",
    price: 1200,
    count: 3,
    description: "lorem lorem lorem",
    category: "textile",
  },
];
